import '@element-plus/components/base/style/css'
import '@element-plus/theme-chalk/ty-color-picker.css'
import '@element-plus/components/color-picker-panel/style/css'
import '@element-plus/components/input/style/css'
import '@element-plus/components/button/style/css'
