import '@teamway-ui/components/base/style/css'
import '@teamway-ui/theme-chalk/ty-table.css'
import '@teamway-ui/components/checkbox/style/css'
import '@teamway-ui/components/tooltip/style/css'
import '@teamway-ui/components/scrollbar/style/css'
