import '@element-plus/components/base/style/css'
import '@element-plus/theme-chalk/ty-container.css'
import '@element-plus/theme-chalk/ty-aside.css'
import '@element-plus/theme-chalk/ty-footer.css'
import '@element-plus/theme-chalk/ty-header.css'
import '@element-plus/theme-chalk/ty-main.css'
