import '@teamway-ui/components/base/style/css'
import '@teamway-ui/theme-chalk/ty-container.css'
import '@teamway-ui/theme-chalk/ty-aside.css'
import '@teamway-ui/theme-chalk/ty-footer.css'
import '@teamway-ui/theme-chalk/ty-header.css'
import '@teamway-ui/theme-chalk/ty-main.css'
